# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res/MainWidget.ui',
# licensing of 'res/MainWidget.ui' applies.
#
# Created: Thu Apr 25 17:07:32 2019
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(550, 286)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/chip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWidget.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(MainWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_serial = QtWidgets.QGroupBox(MainWidget)
        self.groupBox_serial.setObjectName("groupBox_serial")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_serial)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidgetAvailablePorts = QtWidgets.QListWidget(self.groupBox_serial)
        self.listWidgetAvailablePorts.setObjectName("listWidgetAvailablePorts")
        self.verticalLayout_2.addWidget(self.listWidgetAvailablePorts)
        self.pushButtonConnect = QtWidgets.QPushButton(self.groupBox_serial)
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.verticalLayout_2.addWidget(self.pushButtonConnect)
        self.plainTextEditSerialLog = QtWidgets.QPlainTextEdit(self.groupBox_serial)
        self.plainTextEditSerialLog.setObjectName("plainTextEditSerialLog")
        self.verticalLayout_2.addWidget(self.plainTextEditSerialLog)
        self.horizontalLayout.addWidget(self.groupBox_serial)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_wifi = QtWidgets.QGroupBox(MainWidget)
        self.groupBox_wifi.setObjectName("groupBox_wifi")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_wifi)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_wifi)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEditSSID = QtWidgets.QLineEdit(self.groupBox_wifi)
        self.lineEditSSID.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEditSSID.setObjectName("lineEditSSID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditSSID)
        self.label_2 = QtWidgets.QLabel(self.groupBox_wifi)
        self.label_2.setToolTip("")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEditAPPassword = QtWidgets.QLineEdit(self.groupBox_wifi)
        self.lineEditAPPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditAPPassword.setObjectName("lineEditAPPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditAPPassword)
        self.pushButtonAddWiFiAP = QtWidgets.QPushButton(self.groupBox_wifi)
        self.pushButtonAddWiFiAP.setObjectName("pushButtonAddWiFiAP")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pushButtonAddWiFiAP)
        self.verticalLayout.addWidget(self.groupBox_wifi)
        self.groupBoxWebService = QtWidgets.QGroupBox(MainWidget)
        self.groupBoxWebService.setObjectName("groupBoxWebService")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBoxWebService)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBoxWebService)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEditWebServiceAddress = QtWidgets.QLineEdit(self.groupBoxWebService)
        self.lineEditWebServiceAddress.setObjectName("lineEditWebServiceAddress")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditWebServiceAddress)
        self.label_4 = QtWidgets.QLabel(self.groupBoxWebService)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEditToken = QtWidgets.QLineEdit(self.groupBoxWebService)
        self.lineEditToken.setObjectName("lineEditToken")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditToken)
        self.pushButtonSetWebService = QtWidgets.QPushButton(self.groupBoxWebService)
        self.pushButtonSetWebService.setObjectName("pushButtonSetWebService")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pushButtonSetWebService)
        self.verticalLayout.addWidget(self.groupBoxWebService)
        self.pushButtonShowSettings = QtWidgets.QPushButton(MainWidget)
        self.pushButtonShowSettings.setObjectName("pushButtonShowSettings")
        self.verticalLayout.addWidget(self.pushButtonShowSettings)
        self.pushButtonLoadSettings = QtWidgets.QPushButton(MainWidget)
        self.pushButtonLoadSettings.setObjectName("pushButtonLoadSettings")
        self.verticalLayout.addWidget(self.pushButtonLoadSettings)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(MainWidget)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        MainWidget.setWindowTitle(QtWidgets.QApplication.translate("MainWidget", "PC Client", None, -1))
        self.groupBox_serial.setTitle(QtWidgets.QApplication.translate("MainWidget", "SerialPort", None, -1))
        self.pushButtonConnect.setText(QtWidgets.QApplication.translate("MainWidget", "Connect", None, -1))
        self.groupBox_wifi.setTitle(QtWidgets.QApplication.translate("MainWidget", "Add WiFi AccessPoint", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWidget", "SSID", None, -1))
        self.lineEditSSID.setPlaceholderText(QtWidgets.QApplication.translate("MainWidget", "Enter Access Point SSID", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWidget", "Password", None, -1))
        self.lineEditAPPassword.setPlaceholderText(QtWidgets.QApplication.translate("MainWidget", "Enter Access Point password", None, -1))
        self.pushButtonAddWiFiAP.setText(QtWidgets.QApplication.translate("MainWidget", "Add Access Point", None, -1))
        self.groupBoxWebService.setTitle(QtWidgets.QApplication.translate("MainWidget", "Set Web Service", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWidget", "Address", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWidget", "Token", None, -1))
        self.pushButtonSetWebService.setText(QtWidgets.QApplication.translate("MainWidget", "Set Web Service", None, -1))
        self.pushButtonShowSettings.setText(QtWidgets.QApplication.translate("MainWidget", "Show settings", None, -1))
        self.pushButtonLoadSettings.setText(QtWidgets.QApplication.translate("MainWidget", "Load settings", None, -1))

import resources_rc
