# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res\MainWidget.ui',
# licensing of 'res\MainWidget.ui' applies.
#
# Created: Wed Dec 11 22:16:09 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(886, 661)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/chip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWidget.setWindowIcon(icon)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(MainWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_serial = QtWidgets.QGroupBox(MainWidget)
        self.groupBox_serial.setObjectName("groupBox_serial")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_serial)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidgetAvailablePorts = QtWidgets.QListWidget(self.groupBox_serial)
        self.listWidgetAvailablePorts.setObjectName("listWidgetAvailablePorts")
        self.verticalLayout_2.addWidget(self.listWidgetAvailablePorts)
        self.pushButtonConnect = QtWidgets.QPushButton(self.groupBox_serial)
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.verticalLayout_2.addWidget(self.pushButtonConnect)
        self.plainTextEditSerialLog = QtWidgets.QPlainTextEdit(self.groupBox_serial)
        self.plainTextEditSerialLog.setObjectName("plainTextEditSerialLog")
        self.verticalLayout_2.addWidget(self.plainTextEditSerialLog)
        self.horizontalLayout_2.addWidget(self.groupBox_serial)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_wifi = QtWidgets.QGroupBox(MainWidget)
        self.groupBox_wifi.setObjectName("groupBox_wifi")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_wifi)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_wifi)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEditSSID = QtWidgets.QLineEdit(self.groupBox_wifi)
        self.lineEditSSID.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEditSSID.setObjectName("lineEditSSID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditSSID)
        self.label_2 = QtWidgets.QLabel(self.groupBox_wifi)
        self.label_2.setToolTip("")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEditAPPassword = QtWidgets.QLineEdit(self.groupBox_wifi)
        self.lineEditAPPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditAPPassword.setObjectName("lineEditAPPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditAPPassword)
        self.pushButtonAddWiFiAP = QtWidgets.QPushButton(self.groupBox_wifi)
        self.pushButtonAddWiFiAP.setObjectName("pushButtonAddWiFiAP")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pushButtonAddWiFiAP)
        self.verticalLayout.addWidget(self.groupBox_wifi)
        self.groupBoxWebService = QtWidgets.QGroupBox(MainWidget)
        self.groupBoxWebService.setObjectName("groupBoxWebService")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBoxWebService)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBoxWebService)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEditWebServiceAddress = QtWidgets.QLineEdit(self.groupBoxWebService)
        self.lineEditWebServiceAddress.setObjectName("lineEditWebServiceAddress")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditWebServiceAddress)
        self.label_4 = QtWidgets.QLabel(self.groupBoxWebService)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEditToken = QtWidgets.QLineEdit(self.groupBoxWebService)
        self.lineEditToken.setObjectName("lineEditToken")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditToken)
        self.pushButtonSetWebService = QtWidgets.QPushButton(self.groupBoxWebService)
        self.pushButtonSetWebService.setObjectName("pushButtonSetWebService")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pushButtonSetWebService)
        self.verticalLayout.addWidget(self.groupBoxWebService)
        self.groupBoxTestQuery = QtWidgets.QGroupBox(MainWidget)
        self.groupBoxTestQuery.setObjectName("groupBoxTestQuery")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBoxTestQuery)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEditTestQuery = QtWidgets.QLineEdit(self.groupBoxTestQuery)
        self.lineEditTestQuery.setObjectName("lineEditTestQuery")
        self.verticalLayout_3.addWidget(self.lineEditTestQuery)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonTestQuery = QtWidgets.QPushButton(self.groupBoxTestQuery)
        self.pushButtonTestQuery.setObjectName("pushButtonTestQuery")
        self.horizontalLayout.addWidget(self.pushButtonTestQuery)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBoxTestQuery)
        self.groupBoxCtrlQueryTimer = QtWidgets.QGroupBox(MainWidget)
        self.groupBoxCtrlQueryTimer.setObjectName("groupBoxCtrlQueryTimer")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBoxCtrlQueryTimer)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBoxCtrlQueryTimer = QtWidgets.QCheckBox(self.groupBoxCtrlQueryTimer)
        self.checkBoxCtrlQueryTimer.setObjectName("checkBoxCtrlQueryTimer")
        self.verticalLayout_4.addWidget(self.checkBoxCtrlQueryTimer)
        self.verticalLayout.addWidget(self.groupBoxCtrlQueryTimer)
        self.groupBoxBuildInLed = QtWidgets.QGroupBox(MainWidget)
        self.groupBoxBuildInLed.setObjectName("groupBoxBuildInLed")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBoxBuildInLed)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkBoxBuildInLed = QtWidgets.QCheckBox(self.groupBoxBuildInLed)
        self.checkBoxBuildInLed.setObjectName("checkBoxBuildInLed")
        self.verticalLayout_5.addWidget(self.checkBoxBuildInLed)
        self.verticalLayout.addWidget(self.groupBoxBuildInLed)
        self.pushButtonShowSettings = QtWidgets.QPushButton(MainWidget)
        self.pushButtonShowSettings.setObjectName("pushButtonShowSettings")
        self.verticalLayout.addWidget(self.pushButtonShowSettings)
        self.pushButtonLoadSettings = QtWidgets.QPushButton(MainWidget)
        self.pushButtonLoadSettings.setObjectName("pushButtonLoadSettings")
        self.verticalLayout.addWidget(self.pushButtonLoadSettings)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBoxWiFierState = QtWidgets.QGroupBox(MainWidget)
        self.groupBoxWiFierState.setObjectName("groupBoxWiFierState")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBoxWiFierState)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkBoxWiFierState = QtWidgets.QCheckBox(self.groupBoxWiFierState)
        self.checkBoxWiFierState.setEnabled(False)
        self.checkBoxWiFierState.setObjectName("checkBoxWiFierState")
        self.verticalLayout_6.addWidget(self.checkBoxWiFierState)
        self.lineEditWiFierIp = QtWidgets.QLineEdit(self.groupBoxWiFierState)
        self.lineEditWiFierIp.setEnabled(False)
        self.lineEditWiFierIp.setObjectName("lineEditWiFierIp")
        self.verticalLayout_6.addWidget(self.lineEditWiFierIp)
        self.verticalLayout_7.addWidget(self.groupBoxWiFierState)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)

        self.retranslateUi(MainWidget)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        MainWidget.setWindowTitle(QtWidgets.QApplication.translate("MainWidget", "PC Client", None, -1))
        self.groupBox_serial.setTitle(QtWidgets.QApplication.translate("MainWidget", "SerialPort", None, -1))
        self.pushButtonConnect.setText(QtWidgets.QApplication.translate("MainWidget", "Connect", None, -1))
        self.groupBox_wifi.setTitle(QtWidgets.QApplication.translate("MainWidget", "Add WiFi AccessPoint", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWidget", "SSID", None, -1))
        self.lineEditSSID.setPlaceholderText(QtWidgets.QApplication.translate("MainWidget", "Enter Access Point SSID", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWidget", "Password", None, -1))
        self.lineEditAPPassword.setPlaceholderText(QtWidgets.QApplication.translate("MainWidget", "Enter Access Point password", None, -1))
        self.pushButtonAddWiFiAP.setText(QtWidgets.QApplication.translate("MainWidget", "Add Access Point", None, -1))
        self.groupBoxWebService.setTitle(QtWidgets.QApplication.translate("MainWidget", "Set Web Service", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWidget", "Address", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWidget", "Token", None, -1))
        self.pushButtonSetWebService.setText(QtWidgets.QApplication.translate("MainWidget", "Set Web Service", None, -1))
        self.groupBoxTestQuery.setTitle(QtWidgets.QApplication.translate("MainWidget", "Test query", None, -1))
        self.pushButtonTestQuery.setText(QtWidgets.QApplication.translate("MainWidget", "TestQuery", None, -1))
        self.groupBoxCtrlQueryTimer.setTitle(QtWidgets.QApplication.translate("MainWidget", "Query timer control", None, -1))
        self.checkBoxCtrlQueryTimer.setText(QtWidgets.QApplication.translate("MainWidget", "Query timer", None, -1))
        self.groupBoxBuildInLed.setTitle(QtWidgets.QApplication.translate("MainWidget", "Build in led", None, -1))
        self.checkBoxBuildInLed.setText(QtWidgets.QApplication.translate("MainWidget", "Build in led", None, -1))
        self.pushButtonShowSettings.setText(QtWidgets.QApplication.translate("MainWidget", "Show settings", None, -1))
        self.pushButtonLoadSettings.setText(QtWidgets.QApplication.translate("MainWidget", "Load settings", None, -1))
        self.groupBoxWiFierState.setTitle(QtWidgets.QApplication.translate("MainWidget", "WiFier", None, -1))
        self.checkBoxWiFierState.setText(QtWidgets.QApplication.translate("MainWidget", "Connected", None, -1))

import resources_rc
