version: "3"

services:
  app:
    build: backend
    image: rpcs:v0.0.1
    ports:
      - 5000:5000

  nginx:
    build: nginx
    image: nginx_rpcs:v0.0.1
    ports:
      - 8080:80
    depends_on:
      - app
