version: "3"

services:
  app:
    build: backend
    ports:
      - 5000:5000

  nginx:
    build: nginx
    ports:
      - 80:80
    restart: always
    volumes:
      - ./backend/static/:/usr/share/nginx/html
    depends_on:
      - app
