version: "3"

services:
  app:
    image: shnaiderpavel/rpcs_app:v0.0.1
    ports:
      - 5000:5000

  nginx:
    image: shnaiderpavel/rpcs_nginx:v0.0.1
    ports:
      - 80:80
    depends_on:
      - app
